In [1]:
import numpy as np

In [21]:
a1 = np.array([2,1])
a2 = np.array([1,2])
a3 = np.array([-1,0,])
a4 = np.array([0,-1])

b = np.array([6,4])

c1 = -1
c2 = -1
c3 = 0
c4 = 0

In [25]:
# base
aB1 = a1
aB2 = a2

cB1 = c1
cB2 = c2

# não base
aN1 = a3
aN2 = a4

cN1 = c3
cN2 = c4

In [26]:
B = np.array([aB1,aB2])

N = np.array([aN1,aN2])

B = B.T
N = N.T

print("B = ", B)

cB = np.array([cB1,cB2])
print("cB = ", cB)

B =  [[2 1]
 [1 2]]
cB =  [-1 -1]


In [27]:
# inversa de B

detB = np.linalg.det(B)
print("detB = ", np.round(detB,3))

if (detB != 0):
    iB = np.linalg.inv(B)
    print("iB = ", np.round(iB,3))
else:
    print("B não possui inversa!")

detB =  3.0
iB =  [[ 0.667 -0.333]
 [-0.333  0.667]]


In [5]:
a1 = np.array([3,6,2,1])
a2 = np.array([-1,0,0,0])
a3 = np.array([0,0,-1,0])
a4 = np.array([1,5,1,3])

B = np.array([a1,a2,a3,a4])

detB = np.linalg.det(B)
print("detB = ", np.round(detB,3))

if (detB != 0):
    iB = np.linalg.inv(B)
    print("iB = ", np.round(iB,4))
else:
    print("B não possui inversa!")

detB =  -13.0
iB =  [[ 0.     -1.      0.      0.    ]
 [ 0.2308  0.6154  0.3846 -0.0769]
 [-0.     -0.     -1.     -0.    ]
 [-0.3846 -0.6923 -0.3077  0.4615]]


In [3]:
iB[1]

array([ 0.23076923,  0.61538462,  0.38461538, -0.07692308])

In [4]:
B

array([[ 3,  6,  2,  1],
       [-1,  0,  0,  0],
       [ 0,  0, -1,  0],
       [ 1,  5,  1,  3]])

In [7]:
ind = B.dot(iB)

In [8]:
print(np.round(ind,2))

[[ 1.  0. -0.  0.]
 [-0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0. -0. -0.  1.]]


In [14]:
iB[1,1].as_integer_ratio()

(1385722962267845, 2251799813685248)