In [1]:
import numpy as np

# Dados

$
\begin{align*}
\max \ & 5 x_1 + 2 x_2 \\
& -x_1 + x_2 + x_3 = 2 \\
& 8 x_1 + 2 x_2 + x_4 = 17 \\
& x_j \geq 0, \ j = 1, \ldots, 4
\end{align*}
$

In [2]:
a1 = np.array([-1,8])
a2 = np.array([1,2])
a3 = np.array([-1,0,])
a4 = np.array([0,-1])

b = np.array([2,17])

c1 = 5
c2 = 2
c3 = 0
c4 = 0

# iteração 1

In [3]:
# base
aB1 = a1
aB2 = a2

cB1 = c1
cB2 = c2

# não base
aN1 = a3
aN2 = a4

cN1 = c3
cN2 = c4

In [4]:
B = np.array([aB1,aB2])

N = np.array([aN1,aN2])

B = B.T
N = N.T

print("B = ", B)

cB = np.array([cB1,cB2])
print("cB = ", cB)

B =  [[-1  1]
 [ 8  2]]
cB =  [5 2]


In [5]:
# inversa de B

detB = np.linalg.det(B)
print("detB = ", np.round(detB,3))

if (detB != 0):
    iB = np.linalg.inv(B)
    print("iB = ", np.round(iB,3))
else:
    print("B não possui inversa!")

detB =  -10.0
iB =  [[-0.2  0.1]
 [ 0.8  0.1]]


In [6]:
# solução

xB = iB.dot(b.T)
print("xB = ", np.round(xB,2))

temp = 0
for x in xB:
    if x < 0:
        temp += 1
        print("B não é primal viável!")
        break

if temp == 0:
    print("B é primal viável")

z = cB.dot(xB)
print("z = ", np.round(z,2))

xB =  [1.3 3.3]
B é primal viável
z =  13.1


In [7]:
# custos reduzidos

mu = cB.dot(iB)
print("mu = ", np.round(mu,2))

crN1 = mu.dot(aN1.T) - cN1 
print("crN1 = ", np.round(crN1,2))

crN2 = mu.dot(aN2.T) - cN2 
print("crN2 = ", np.round(crN2,2))

if (crN1 < 0 and crN2 < 0):
    print("B é dual viável")
else:
    print("B não é dual viável")

mu =  [0.6 0.7]
crN1 =  -0.6
crN2 =  -0.7
B é dual viável


In [9]:
# escolha do item a entrar na base

# Y = B^{-1} N

Y = iB.dot(N)
print("Y = ", Y)

#yB4 = iB[3].dot(N)
#print("yB4 = ", yB4)

Y =  [[ 0.2 -0.1]
 [-0.8 -0.1]]


$
\min_{j \in J} \left\{ \frac{z_j - c_j}{y_{kj}} \ : \ y_{kj} < 0 \right\}
$

In [10]:
#l =  min_{j \in J} {(z_j - c_j)/y_{kj} : y_{kj} < 0}
# onde k é o indice da coluna que sairá da base e l é o indice coluna que entrará na base 

# a coluna a1 entrará na base na próxima iteração
# a coluna a6 sairá na base na próxima iteração

v1 = crN1/yB4[0]
v2 = crN2/yB4[1]
print(np.round(v1,2))
print(np.round(v2,2))

v = min(v1,v2)
print(np.round(v,2))

0.62
2.0
0.62


In [14]:
# novo problema

a1 = np.array([-1,8,0])
a2 = np.array([1,2,1])
a3 = np.array([-1,0,0])
a4 = np.array([0,-1,0])
a5 = np.array([0,0,-1])

b = np.array([2,17,3])

c1 = 5
c2 = 2
c3 = 0
c4 = 0
c5 = 0

In [21]:
# base
aB1 = a1
aB2 = a2
aB3 = a3

cB1 = c1
cB2 = c2
cB3 = c3

# não base
aN1 = a4
aN2 = a5

cN1 = c4
cN2 = c5

In [22]:
B = np.array([aB1,aB2,aB3])

N = np.array([aN1,aN2])

B = B.T
N = N.T

print("B = ", B)

cB = np.array([cB1,cB2,cB3])
print("cB = ", cB)

B =  [[-1  1 -1]
 [ 8  2  0]
 [ 0  1  0]]
cB =  [5 2 0]


In [23]:
# inversa de B

detB = np.linalg.det(B)
print("detB = ", np.round(detB,3))

if (detB != 0):
    iB = np.linalg.inv(B)
    print("iB = ", np.round(iB,3))
else:
    print("B não possui inversa!")

detB =  -8.0
iB =  [[ 0.     0.125 -0.25 ]
 [ 0.     0.     1.   ]
 [-1.    -0.125  1.25 ]]


In [24]:
B.dot(iB)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# solução

xB = iB.dot(b.T)
print("xB = ", np.round(xB,2))

temp = 0
for x in xB:
    if x < 0:
        temp += 1
        print("B não é primal viável!")
        break

if temp == 0:
    print("B é primal viável")

z = cB.dot(xB)
print("z = ", np.round(z,2))

xB =  [ 1.38  3.   -0.38]
B não é primal viável!
z =  12.88


In [20]:
# custos reduzidos

mu = cB.dot(iB)
print("mu = ", np.round(mu,2))

crN1 = mu.dot(aN1.T) - cN1 
print("crN1 = ", np.round(crN1,2))

crN2 = mu.dot(aN2.T) - cN2 
print("crN2 = ", np.round(crN2,2))

if (crN1 < 0 and crN2 < 0):
    print("B é dual viável")
else:
    print("B não é dual viável")

mu =  [0.6 0.7 0. ]
crN1 =  -0.6
crN2 =  -0.7
B é dual viável


# iteração 2

In [12]:
# base
aB1 = a2
aB2 = a3
aB3 = a5
aB4 = a1

cB1 = c2
cB2 = c3
cB3 = c5
cB4 = c1

# não base
aN1 = a6
aN2 = a4

cN1 = c6
cN2 = c4

In [13]:
B = np.array([aB1,aB2,aB3,aB4])

N = np.array([aN1,aN2])

B = B.T
N = N.T

print("B = ", B)

cB = np.array([cB1,cB2,cB3,cB4])
print("cB = ", cB)

B =  [[ 3 -1  0  1]
 [ 6  0  0  5]
 [ 2  0 -1  1]
 [ 1  0  0  3]]
cB =  [2 0 0 3]


In [14]:
# inversa de B

detB = np.linalg.det(B)
print("detB = ", detB)

if (detB != 0):
    print("B possui inversa!")
    iB = np.linalg.inv(B)
    print("iB = ", np.round(iB,3))
else:
    print("B não possui inversa!")

detB =  -13.0
B possui inversa!
iB =  [[ 0.     0.231  0.    -0.385]
 [-1.     0.615 -0.    -0.692]
 [-0.     0.385 -1.    -0.308]
 [ 0.    -0.077  0.     0.462]]


In [15]:
# solução

xB = iB.dot(b.T)
print("xB = ", np.round(xB,2))

z = cB.dot(xB)
print("z = ", np.round(z))

temp = 0
for x in xB:
    if x < 0:
        temp += 1
        print("B não é primal viável!")
        break

if temp == 0:
    print("B é primal viável")

xB =  [4.62 5.31 1.69 0.46]
z =  11.0
B é primal viável


In [16]:
# custos reduzidos

mu = cB.dot(iB)
print("mu = ", np.round(mu,2))

crN1 = mu.dot(aN1.T) - cN1 
print("crN1 = ", np.round(crN1,2))

crN2 = mu.dot(aN2.T) - cN2 
print("crN2 = ", np.round(crN2,2))

if (crN1 < 0 and crN2 < 0):
    print("B é dual viável")
else:
    print("B não é dual viável")

mu =  [0.   0.23 0.   0.62]
crN1 =  -0.62
crN2 =  -0.23
B é dual viável


In [1]:
# importando biblioteca
import gurobipy as gp
from gurobipy import GRB

In [4]:
# criando modelo do problema inteiro
mip = gp.Model()

# adicionando variáveis
x3 = mip.addVar(vtype=GRB.BINARY, name="x3")
x5 = mip.addVar(vtype=GRB.BINARY, name="x5")
x6 = mip.addVar(vtype=GRB.BINARY, name="x6")

# adicionando restrições
mip.addConstr(7*x3 + 5*x5 + 3*x6 <= 2)

# definindo função objetivo
mip.setObjective(x3 + x5 + x6, GRB.MAXIMIZE)

# resolvendo o problema
mip.optimize()

# imprimindo valor ótimo
print(mip.objVal)

# imprimindo solução
for v in mip.getVars():
    print(v.varName, v.x)

Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (linux64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 1 rows, 3 columns and 3 nonzeros
Model fingerprint: 0x577ad9d2
Variable types: 0 continuous, 3 integer (3 binary)
Coefficient statistics:
  Matrix range     [3e+00, 7e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [2e+00, 2e+00]
Found heuristic solution: objective -0.0000000
Presolve removed 1 rows and 3 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: -0 
No other solutions better than -0

Optimal solution found (tolerance 1.00e-04)
Best objective -0.000000000000e+00, best bound -0.000000000000e+00, gap 0.0000%
-0.0
x3 0.0
x5 0.0
x6 0.0


In [5]:
mip = gp.Model()

x1 = mip.addVar(vtype=GRB.BINARY, name="x1")
x3 = mip.addVar(vtype=GRB.BINARY, name="x3")
x5 = mip.addVar(vtype=GRB.BINARY, name="x5")
x6 = mip.addVar(vtype=GRB.BINARY, name="x6")

mip.setObjective(2*x1 + x3 + x5 + x6, GRB.MAXIMIZE)

mip.addConstr(12*x1 + 7*x3 + 5*x5 + 3*x6 <= 5)

mip.optimize()

print(mip.objVal)

for v in mip.getVars():
    print(v.varName, v.x)

Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (linux64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 1 rows, 4 columns and 4 nonzeros
Model fingerprint: 0x4fe8ee45
Variable types: 0 continuous, 4 integer (4 binary)
Coefficient statistics:
  Matrix range     [3e+00, 1e+01]
  Objective range  [1e+00, 2e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [5e+00, 5e+00]
Found heuristic solution: objective 1.0000000
Presolve removed 1 rows and 4 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 1 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.000000000000e+00, best bound 1.000000000000e+00, gap 0.0000%
1.0
x1 0.0
x3 0.0
x5 1.0
x6 0.0


In [7]:
mip = gp.Model()

x1 = mip.addVar(vtype=GRB.BINARY, name="x1")
x2 = mip.addVar(vtype=GRB.BINARY, name="x2")
x3 = mip.addVar(vtype=GRB.BINARY, name="x3")
x5 = mip.addVar(vtype=GRB.BINARY, name="x5")
x6 = mip.addVar(vtype=GRB.BINARY, name="x6")

mip.setObjective(2*x1 + x2 + x3 + x5 + x6, GRB.MAXIMIZE)

mip.addConstr(12*x1 + 9*x2 + 7*x3 + 5*x5 + 3*x6 <= 9)

mip.optimize()

print(mip.objVal)

for v in mip.getVars():
    print(v.varName, v.x)

Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (linux64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 1 rows, 5 columns and 5 nonzeros
Model fingerprint: 0x867de4d2
Variable types: 0 continuous, 5 integer (5 binary)
Coefficient statistics:
  Matrix range     [3e+00, 1e+01]
  Objective range  [1e+00, 2e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [9e+00, 9e+00]
Found heuristic solution: objective 1.0000000
Presolve removed 1 rows and 5 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.00 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 2 1 

Optimal solution found (tolerance 1.00e-04)
Best objective 2.000000000000e+00, best bound 2.000000000000e+00, gap 0.0000%
2.0
x1 0.0
x2 0.0
x3 0.0
x5 1.0
x6 1.0
