In [1]:
# importando biblioteca
import numpy as np
import gurobipy as gp
from gurobipy import GRB

In [3]:
# raiz

# modelo
m0 = gp.Model()

# variáveis
x1 = m0.addVar(name="x1")
x2 = m0.addVar(name="x2")

# restrições
m0.addConstr(4*x1 + 9*x2 <= 35)
m0.addConstr(x1 <= 6)
m0.addConstr(-x1 + 3*x2 <= -1)
#m0.addConstr(3*x1 - 3*x2 <= 19)

# função objetivo
m0.setObjective(9*x1 + 5*x2, GRB.MAXIMIZE)

m0.write('lista05_ex2_raiz.lp')

# resolvendo o problema
m0.optimize()

# valor ótimo
print("otimo: ", np.round(m0.objval,2))

# solução
for v in m0.getVars():
    print(v.varName, np.round(v.x,2))

Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (linux64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 3 rows, 2 columns and 5 nonzeros
Model fingerprint: 0xfc0bdad0
Coefficient statistics:
  Matrix range     [1e+00, 9e+00]
  Objective range  [5e+00, 9e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 4e+01]
Presolve removed 1 rows and 0 columns
Presolve time: 0.01s
Presolved: 2 rows, 2 columns, 4 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    7.8750000e+01   6.875000e-01   0.000000e+00      0s
       1    6.0111111e+01   0.000000e+00   0.000000e+00      0s

Solved in 1 iterations and 0.01 seconds
Optimal objective  6.011111111e+01
otimo:  60.11
x1 6.0
x2 1.22


In [4]:
# x2 <= 1

# modelo
m1 = gp.Model()

# variáveis
x1 = m1.addVar(name="x1")
x2 = m1.addVar(name="x2")

# restrições
m1.addConstr(4*x1 + 9*x2 <= 35)
m1.addConstr(x1 <= 6)
m1.addConstr(-x1 + 3*x2 <= -1)
#m1.addConstr(3*x1 - 3*x2 <= 19)
m1.addConstr(x2 <= 1)

# função objetivo
m1.setObjective(9*x1 + 5*x2, GRB.MAXIMIZE)

m1.write('lista05_ex2_node1.lp')

# resolvendo o problema
m1.optimize()

# valor ótimo
print("otimo: ", np.round(m1.objval,2))

# solução
for v in m1.getVars():
    print(v.varName, np.round(v.x,2))

Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (linux64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 4 rows, 2 columns and 6 nonzeros
Model fingerprint: 0x91df0026
Coefficient statistics:
  Matrix range     [1e+00, 9e+00]
  Objective range  [5e+00, 9e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 4e+01]
Presolve removed 4 rows and 2 columns
Presolve time: 0.00s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    5.9000000e+01   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.01 seconds
Optimal objective  5.900000000e+01
otimo:  59.0
x1 6.0
x2 1.0


In [5]:
# x2 >= 2

# modelo
m2 = gp.Model()

# variáveis
x1 = m2.addVar(name="x1")
x2 = m2.addVar(name="x2")

# restrições
m2.addConstr(4*x1 + 9*x2 <= 35)
m2.addConstr(x1 <= 6)
m2.addConstr(-x1 + 3*x2 <= -1)
#m2.addConstr(3*x1 - 3*x2 <= 19)
m2.addConstr(-x2 <= -2)

# função objetivo
m2.setObjective(9*x1 + 5*x2, GRB.MAXIMIZE)

m2.write('lista05_ex2_node2.lp')

# resolvendo o problema
m2.optimize()

# valor ótimo
#print("otimo: ", np.round(m2.objval,2))

# solução
#for v in m2.getVars():
#    print(v.varName, np.round(v.x,2))

Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (linux64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 4 rows, 2 columns and 6 nonzeros
Model fingerprint: 0x09ba02c2
Coefficient statistics:
  Matrix range     [1e+00, 9e+00]
  Objective range  [5e+00, 9e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 4e+01]
Presolve removed 2 rows and 0 columns
Presolve time: 0.00s

Solved in 0 iterations and 0.00 seconds
Infeasible or unbounded model


In [6]:
# raiz

# modelo
m = gp.Model()

# variáveis
x1 = m.addVar(name="x1")
x2 = m.addVar(name="x2")

# restrições
m.addConstr(4*x1 + 9*x2 <= 35)
m.addConstr(x1 <= 6)
m.addConstr(-x1 + 3*x2 <= -1)

# função objetivo
m.setObjective(9*x1 + 5*x2, GRB.MAXIMIZE)

m.write('lista05_ex2.lp')

# resolvendo o problema
m.optimize()

# valor ótimo
print("otimo: ", np.round(m.objval,2))

# solução
for v in m.getVars():
    print(v.varName, np.round(v.x,2))

Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (linux64)
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 3 rows, 2 columns and 5 nonzeros
Model fingerprint: 0xfc0bdad0
Coefficient statistics:
  Matrix range     [1e+00, 9e+00]
  Objective range  [5e+00, 9e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 4e+01]
Presolve removed 1 rows and 0 columns
Presolve time: 0.00s
Presolved: 2 rows, 2 columns, 4 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    7.8750000e+01   6.875000e-01   0.000000e+00      0s
       1    6.0111111e+01   0.000000e+00   0.000000e+00      0s

Solved in 1 iterations and 0.01 seconds
Optimal objective  6.011111111e+01
otimo:  60.11
x1 6.0
x2 1.22


In [7]:
a1 = np.array([4,1,-1])
a2 = np.array([9,0,3])
a3 = np.array([1,0,0])
a4 = np.array([0,1,0])
a5 = np.array([0,0,1])

b = np.array([35,6,-1])

c1 = 9
c2 = 5
c3 = 0
c4 = 0
c5 = 0

In [8]:
# base
aB1 = a1
aB2 = a2
aB3 = a3

cB1 = c1
cB2 = c2
cB3 = c3

# não base
aN1 = a4
aN2 = a5

cN1 = c4
cN2 = c5

In [9]:
B = np.array([aB1,aB2,aB3])

N = np.array([aN1,aN2])

B = B.T
N = N.T

print("B = ", B)

cB = np.array([cB1,cB2,cB3])
print("cB = ", cB)

B =  [[ 4  9  1]
 [ 1  0  0]
 [-1  3  0]]
cB =  [9 5 0]


In [10]:
# inversa de B

detB = np.linalg.det(B)
print("detB = ", np.round(detB,3))

if (detB != 0):
    iB = np.linalg.inv(B)
    print("iB = ", np.round(iB,3))
else:
    print("B não possui inversa!")

detB =  3.0
iB =  [[ 0.     1.     0.   ]
 [ 0.     0.333  0.333]
 [ 1.    -7.    -3.   ]]


In [11]:
# solução
# verificar se B é primal viável

xB = iB.dot(b.T)
print("xB = ", np.round(xB,2))

temp = 0
for x in xB:
    if x < 0:
        temp += 1
        print("B não é primal viável!")
        break

if temp == 0:
    print("B é primal viável")

z = cB.dot(xB)
print("z = ", np.round(z,2))

xB =  [ 6.    1.67 -4.  ]
B não é primal viável!
z =  62.33


In [13]:
# custos reduzidos

mu = cB.dot(iB)
print("mu = ", np.round(mu,2))

crN1 = mu.dot(aN1.T) - cN1 
print("crN1 = ", np.round(crN1,2))

crN2 = mu.dot(aN2.T) - cN2 
print("crN2 = ", np.round(crN2,2))

if (crN1 >= 0 and crN2 >= 0):
    print("B é dual viável")
else:
    print("B não é dual viável")

mu =  [ 0.   10.67  1.67]
crN1 =  10.67
crN2 =  1.67
B é dual viável


In [16]:
# escolha do item a entrar na base

# Y = B^{-1} N

Y = iB.dot(N)
print("Y = ", np.round(Y,2))
print('')

yB = iB[2].dot(N)
print("yB = ", yB)

Y =  [[ 1.    0.  ]
 [ 0.33  0.33]
 [-7.   -3.  ]]

yB =  [-7. -3.]


In [17]:
#l =  max_{j \in J} {(z_j - c_j)/y_{kj} : y_{kj} < 0}
# onde k é o indice da coluna que sairá da base e l é o indice coluna que entrará na base 

v1 = crN1/yB[0]
v2 = crN2/yB[1]
print(np.round(v1,2))
print(np.round(v2,2))

v = max(v1,v2)
print(np.round(v,2))

# a coluna a5 entrará na base na próxima iteração
# a coluna a3 sairá na base na próxima iteração

-1.52
-0.56
-0.56


In [18]:
# base
aB1 = a1
aB2 = a2
aB3 = a5

cB1 = c1
cB2 = c2
cB3 = c5

# não base
aN1 = a4
aN2 = a3

cN1 = c4
cN2 = c3

In [20]:
B = np.array([aB1,aB2,aB3])

N = np.array([aN1,aN2])

B = B.T
N = N.T

print("B = ", B)
print('')

cB = np.array([cB1,cB2,cB3])
print("cB = ", cB)

B =  [[ 4  9  0]
 [ 1  0  0]
 [-1  3  1]]

cB =  [9 5 0]


In [21]:
# inversa de B

detB = np.linalg.det(B)
print("detB = ", np.round(detB,3))

if (detB != 0):
    iB = np.linalg.inv(B)
    print("iB = ", np.round(iB,3))
else:
    print("B não possui inversa!")

detB =  -9.0
iB =  [[ 0.     1.     0.   ]
 [ 0.111 -0.444  0.   ]
 [-0.333  2.333  1.   ]]


In [22]:
# solução
# verificar se B é primal viável

xB = iB.dot(b.T)
print("xB = ", np.round(xB,2))

temp = 0
for x in xB:
    if x < 0:
        temp += 1
        print("B não é primal viável!")
        break

if temp == 0:
    print("B é primal viável")

z = cB.dot(xB)
print("z = ", np.round(z,2))

xB =  [6.   1.22 1.33]
B é primal viável
z =  60.11


In [23]:
# custos reduzidos

mu = cB.dot(iB)
print("mu = ", np.round(mu,2))

crN1 = mu.dot(aN1.T) - cN1 
print("crN1 = ", np.round(crN1,2))

crN2 = mu.dot(aN2.T) - cN2 
print("crN2 = ", np.round(crN2,2))

if (crN1 >= 0 and crN2 >= 0):
    print("B é dual viável")
else:
    print("B não é dual viável")

mu =  [0.56 6.78 0.  ]
crN1 =  6.78
crN2 =  0.56
B é dual viável


# logo B é ótima

$x_2$ é fracionária, assim criaremos dois novos problemas:

- node1

\begin{align*}
\max \ & 9 x_1 + 5 x_2 \\
& 4 x_1 + 9 x_2 \leq 9 \\
& x_1 \leq 6 \\
& - x_1 + 3 x_2 \leq -1 \\
& x_2 \leq 1 \\
& x_j \geq 0, \ j = 1, \ldots, 5.
\end{align*}

- node2

\begin{align*}
\max \ & 9 x_1 + 5 x_2 \\
& 4 x_1 + 9 x_2 \leq 9 \\
& x_1 \leq 6 \\
& - x_1 + 3 x_2 \leq -1 \\
& x_2 \geq 2 \\
& x_j \geq 0, \ j = 1, \ldots, 5.
\end{align*}

# Resolvendo node1

In [24]:
a1 = np.array([4,1,-1,0])
a2 = np.array([9,0,3,1])
a3 = np.array([1,0,0,0])
a4 = np.array([0,1,0,0])
a5 = np.array([0,0,1,0])
a6 = np.array([0,0,0,1])

b = np.array([35,6,-1,1])

c1 = 9
c2 = 5
c3 = 0
c4 = 0
c5 = 0
c6 = 0

In [25]:
# base
aB1 = a1
aB2 = a2
aB3 = a5
aB4 = a6

cB1 = c1
cB2 = c2
cB3 = c5
cB4 = c6

# não base
aN1 = a4
aN2 = a3

cN1 = c4
cN2 = c3

In [26]:
B = np.array([aB1,aB2,aB3,aB4])

N = np.array([aN1,aN2])

B = B.T
N = N.T

print("B = ", B)

cB = np.array([cB1,cB2,cB3,cB4])
print("cB = ", cB)

B =  [[ 4  9  0  0]
 [ 1  0  0  0]
 [-1  3  1  0]
 [ 0  1  0  1]]
cB =  [9 5 0 0]


In [27]:
# inversa de B

detB = np.linalg.det(B)
print("detB = ", np.round(detB,3))

if (detB != 0):
    iB = np.linalg.inv(B)
    print("iB = ", np.round(iB,3))
else:
    print("B não possui inversa!")

detB =  -9.0
iB =  [[ 0.     1.     0.     0.   ]
 [ 0.111 -0.444  0.     0.   ]
 [-0.333  2.333  1.     0.   ]
 [-0.111  0.444  0.     1.   ]]


In [28]:
# solução

xB = iB.dot(b.T)
print("xB = ", np.round(xB,2))

temp = 0
for x in xB:
    if x < 0:
        temp += 1
        print("B não é primal viável!")
        break

if temp == 0:
    print("B é primal viável")

z = cB.dot(xB)
print("z = ", np.round(z,2))

xB =  [ 6.    1.22  1.33 -0.22]
B não é primal viável!
z =  60.11


In [29]:
# custos reduzidos

mu = cB.dot(iB)
print("mu = ", np.round(mu,2))

crN1 = mu.dot(aN1.T) - cN1 
print("crN1 = ", np.round(crN1,2))

crN2 = mu.dot(aN2.T) - cN2 
print("crN2 = ", np.round(crN2,2))

if (crN1 >= 0 and crN2 >= 0):
    print("B é dual viável")
else:
    print("B não é dual viável")

mu =  [0.56 6.78 0.   0.  ]
crN1 =  6.78
crN2 =  0.56
B é dual viável


In [31]:
# escolha do item a entrar na base

# Y = B^{-1} N

Y = iB.dot(N)
print("Y = ", Y)
print('')

yB = iB[3].dot(N)
print("yB = ", yB)

Y =  [[ 1.00000000e+00  4.51028104e-17]
 [-4.44444444e-01  1.11111111e-01]
 [ 2.33333333e+00 -3.33333333e-01]
 [ 4.44444444e-01 -1.11111111e-01]]

yB =  [ 0.44444444 -0.11111111]


In [32]:
#l =  max_{j \in J} {(z_j - c_j)/y_{kj} : y_{kj} < 0}
# onde k é o indice da coluna que sairá da base e l é o indice coluna que entrará na base 

#if (yB[0] < 0):
#    v1 = crN1/yB[0]
#    print(np.round(v1,2))
    
#if (yB[1] < 0):
#    v2 = crN2/yB[1]
#    print(np.round(v2,2))


#v = max(v1,v2)
#print(np.round(v,2))

# a coluna a3 entrará na base na próxima iteração
# a coluna a6 sairá na base na próxima iteração

-5.0
-1.52


In [33]:
# base
aB1 = a1
aB2 = a2
aB3 = a5
aB4 = a3

cB1 = c1
cB2 = c2
cB3 = c5
cB4 = c3

# não base
aN1 = a4
aN2 = a6

cN1 = c4
cN2 = c6

In [34]:
B = np.array([aB1,aB2,aB3,aB4])

N = np.array([aN1,aN2])

B = B.T
N = N.T

print("B = ", B)

cB = np.array([cB1,cB2,cB3,cB4])
print("cB = ", cB)

B =  [[ 4  9  0  1]
 [ 1  0  0  0]
 [-1  3  1  0]
 [ 0  1  0  0]]
cB =  [9 5 0 0]


In [35]:
# inversa de B

detB = np.linalg.det(B)
print("detB = ", np.round(detB,3))

if (detB != 0):
    iB = np.linalg.inv(B)
    print("iB = ", np.round(iB,3))
else:
    print("B não possui inversa!")

detB =  1.0
iB =  [[ 0.  1.  0.  0.]
 [ 0. -0.  0.  1.]
 [ 0.  1.  1. -3.]
 [ 1. -4. -0. -9.]]


In [36]:
# solução

xB = iB.dot(b.T)
print("xB = ", np.round(xB,2))

temp = 0
for x in xB:
    if x < 0:
        temp += 1
        print("B não é primal viável!")
        break

if temp == 0:
    print("B é primal viável")

z = cB.dot(xB)
print("z = ", np.round(z,2))

xB =  [6. 1. 2. 2.]
B é primal viável
z =  59.0


In [37]:
# custos reduzidos

mu = cB.dot(iB)
print("mu = ", np.round(mu,2))

crN1 = mu.dot(aN1.T) - cN1 
print("crN1 = ", np.round(crN1,2))

crN2 = mu.dot(aN2.T) - cN2 
print("crN2 = ", np.round(crN2,2))

if (crN1 > 0 and crN2 > 0):
    print("B é dual viável")
else:
    print("B não é dual viável")

mu =  [0. 9. 0. 5.]
crN1 =  9.0
crN2 =  5.0
B é dual viável


# logo B é dual viável