In [2]:
import numpy as np

## item a)

$
\begin{align*}
\min \ & 3 x_1 + 2 x_2 \\
& x_1 + 3 x_2 - x_3 = 9 \\
& 5 x_1 + 6 x_2 - x_4 = 30 \\
& x_1 + 2 x_2 - x_5 = 8 \\
& x_j \geq 0, \ j = 1, \ldots, 5
\end{align*}
$

In [3]:
# instancia

a1 = np.array([1,5,1])
a2 = np.array([3,6,2])
a3 = np.array([-1,0,0])
a4 = np.array([0,-1,0])
a5 = np.array([0,0,-1])

b = np.array([9,30,8])

c1 = 3
c2 = 2
c3 = 0
c4 = 0
c5 = 0

In [4]:
# base

aB1 = a2
aB2 = a3
aB3 = a5

cB1 = c2
cB2 = c3
cB3 = c5

# não base

aN1 = a1
    aN2 = a4

cN1 = c1
cN2 = c4

In [5]:
B = np.array([aB1,aB2,aB3])

N = np.array([aN1,aN2])

B = B.T
N = N.T

print("B = ", B)

cB = np.array([cB1,cB2,cB3])
print("cB = ", cB)

B =  [[ 3 -1  0]
 [ 6  0  0]
 [ 2  0 -1]]
cB =  [2 0 0]


In [6]:
# inversa de B

detB = np.linalg.det(B)
print("detB = ", np.round(detB,3))

if (detB != 0):
    iB = np.linalg.inv(B)
    print("iB = ", np.round(iB,3))
else:
    print("B não possui inversa!")

detB =  -6.0
iB =  [[ 0.     0.167  0.   ]
 [-1.     0.5   -0.   ]
 [-0.     0.333 -1.   ]]


In [7]:
# solução

xB = iB.dot(b.T)
print("xB = ", np.round(xB,2))

temp = 0
for x in xB:
    if x < 0:
        temp += 1
        print("B não é primal viável!")
        break

if temp == 0:
    print("B é primal viável")
    z = cB.dot(xB)
    print("z = ", np.round(z,2))

xB =  [5. 6. 2.]
B é primal viável
z =  10.0


In [8]:
# custos reduzidos

mu = cB.dot(iB)
print("mu = ", np.round(mu,2))

crN1 = mu.dot(aN1.T) - cN1 
print("crN1 = ", np.round(crN1,2))

crN2 = mu.dot(aN2.T) - cN2 
print("crN2 = ", np.round(crN2,2))

if (crN1 < 0 and crN2 < 0):
    print("B é dual viável")
else:
    print("B não é dual viável")

mu =  [0.   0.33 0.  ]
crN1 =  -1.33
crN2 =  -0.33
B é dual viável


Como $B$ é primal viável e dual viável para o problema, $B$ é uma base ótima para o problema.

## item b)

$
\begin{align*}
\min \ & 3 x_1 + 2 x_2 \\
& x_1 + 3 x_2 - x_3 = 9 \\
& 5 x_1 + 6 x_2 - x_4 = 30 \\
& x_1 + 2 x_2 - x_5 = 8 \\
& 3 x_1 + x_2 - x_6 = 6 \\
& x_j \geq 0, \ j = 1, \ldots, 5
\end{align*}
$

In [10]:
# instância

a1 = np.array([1,5,1,3])
a2 = np.array([3,6,2,1])
a3 = np.array([-1,0,0,0])
a4 = np.array([0,-1,0,0])
a5 = np.array([0,0,-1,0])
a6 = np.array([0,0,0,-1])

b = np.array([9,30,8,6])

c1 = 3
c2 = 2
c3 = 0
c4 = 0
c5 = 0
c6 = 0

In [11]:
# base
aB1 = a2
aB2 = a3
aB3 = a5
aB4 = a6

cB1 = c2
cB2 = c3
cB3 = c5
cB4 = c6

# não base
aN1 = a1
aN2 = a4

cN1 = c1
cN2 = c4

In [12]:
B = np.array([aB1,aB2,aB3,aB4])

N = np.array([aN1,aN2])

B = B.T
N = N.T

print("B = ", B)

cB = np.array([cB1,cB2,cB3,cB4])
print("cB = ", cB)

B =  [[ 3 -1  0  0]
 [ 6  0  0  0]
 [ 2  0 -1  0]
 [ 1  0  0 -1]]
cB =  [2 0 0 0]


In [13]:
# inversa de B

detB = np.linalg.det(B)
print("detB = ", np.round(detB,3))

if (detB != 0):
    iB = np.linalg.inv(B)
    print("iB = ", np.round(iB,3))
else:
    print("B não possui inversa!")

detB =  6.0
iB =  [[ 0.     0.167  0.     0.   ]
 [-1.     0.5   -0.    -0.   ]
 [-0.     0.333 -1.    -0.   ]
 [-0.     0.167 -0.    -1.   ]]


In [14]:
# solução

xB = iB.dot(b.T)
print("xB = ", np.round(xB,2))

temp = 0
for x in xB:
    if x < 0:
        temp += 1
        print("B não é primal viável!")
        break

if temp == 0:
    print("B é primal viável")
    z = cB.dot(xB)
    print("z = ", np.round(z,2))

xB =  [ 5.  6.  2. -1.]
B não é primal viável!


In [15]:
# custos reduzidos

mu = cB.dot(iB)
print("mu = ", np.round(mu,2))

crN1 = mu.dot(aN1.T) - cN1 
print("crN1 = ", np.round(crN1,2))

crN2 = mu.dot(aN2.T) - cN2 
print("crN2 = ", np.round(crN2,2))

if (crN1 < 0 and crN2 < 0):
    print("B é dual viável")
else:
    print("B não é dual viável")

mu =  [0.   0.33 0.   0.  ]
crN1 =  -1.33
crN2 =  -0.33
B é dual viável


## $x_6$ sairá da base

In [16]:
# escolha do item a entrar na base

# Y = B^{-1} N

# Y = iB.dot(N)
# print("Y = ", Y)

yB4 = iB[3].dot(N)
print("yB4 = ", yB4)

yB4 =  [-2.16666667 -0.16666667]


$
\min_{j \in J} \left\{ \frac{z_j - c_j}{y_{kj}} \ : \ y_{kj} < 0 \right\}
$

In [17]:
#l =  min_{j \in J} {(z_j - c_j)/y_{kj} : y_{kj} < 0}
# onde k é o indice da coluna que sairá da base e l é o indice coluna que entrará na base 

# a coluna a1 entrará na base na próxima iteração
# a coluna a6 sairá na base na próxima iteração

v1 = crN1/yB4[0]
v2 = crN2/yB4[1]
print(np.round(v1,2))
print(np.round(v2,2))

v = min(v1,v2)
print(np.round(v,2))

0.62
2.0
0.62


### nova base

In [18]:
# instância

aB1 = a2
aB2 = a3
aB3 = a5
aB4 = a1

cB1 = c2
cB2 = c3
cB3 = c5
cB4 = c1

# não base
aN1 = a6
aN2 = a4

cN1 = c6
cN2 = c4

In [19]:
# nova base

B = np.array([aB1,aB2,aB3,aB4])

N = np.array([aN1,aN2])

B = B.T
N = N.T

print("B = ", B)

cB = np.array([cB1,cB2,cB3,cB4])
print("cB = ", cB)

B =  [[ 3 -1  0  1]
 [ 6  0  0  5]
 [ 2  0 -1  1]
 [ 1  0  0  3]]
cB =  [2 0 0 3]


In [20]:
# inversa de B

detB = np.linalg.det(B)
print("detB = ", np.round(detB,3))

if (detB != 0):
    iB = np.linalg.inv(B)
    print("iB = ", np.round(iB,3))
else:
    print("B não possui inversa!")

detB =  -13.0
iB =  [[ 0.     0.231  0.    -0.385]
 [-1.     0.615 -0.    -0.692]
 [-0.     0.385 -1.    -0.308]
 [ 0.    -0.077  0.     0.462]]


In [22]:
# solução

xB = iB.dot(b.T)
print("xB = ", np.round(xB,2))

temp = 0
for x in xB:
    if x < 0:
        temp += 1
        print("B não é primal viável!")
        break

if temp == 0:
    print("B é primal viável")
    z = cB.dot(xB)
    print("z = ", np.round(z,2))

xB =  [4.62 5.31 1.69 0.46]
B é primal viável
z =  10.62


Temos que $B$ é uma base primal viável. Como $B$ também é dual viável, $B$ é uma base ótima para o problema.